{
 "title": "Coronavirus",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Total Cases Worldwide",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "total_cases{country=\"Total:\"}"
    }
   ]
  },
  {
   "title": "Total Cases Per Million Population Worldwide",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "total_cases_per_one_million_population{country=\"Total:\"}"
    }
   ]
  },
  {
   "title": "Total Active Cases Worldwide",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "active_cases{country=\"Total:\"}"
    }
   ]
  },
  {
   "title": "Total Deaths Worldwide",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "total_deaths{country=\"Total:\"}"
    }
   ]
  },
  {
   "title": "Total Cases > 2K",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(total_cases{country!=\"Total:\"}) > 2000",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Increase of cases (Over 10 minutes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(increase(total_cases{country!=\"Total:\"}[10m])) ",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Increase of New Cases (Hourly)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "increase(new_cases[1h])", "legendFormat": "{{country}}" }
   ]
  },
  {
   "title": "Increase of New Deaths (Hourly)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "increase(new_deaths[1h])", "legendFormat": "{{country}}" }
   ]
  }
 ]
}