spring:
  datasource:
    url: jdbc:mariadb://192.168.1.55:3306/stats
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jmx:
    enabled: true
  main:
    banner-mode: "off"
  application:
    name: "stats-monitor"
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    ROOT: INFO

server:
  port: 8080

# Monitoring
management:
  server:
    port: 8081
    ssl:
      enabled: false
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
